#!/bin/sh

set -e

usage() {
    printf "Usage: panboticon bootstrap \e[4mname\e[0m[...]\n" >&2
    printf "  \e[4mname\e[0m  name of the Panboticon instance to bootstrap\n" >&2
    exit "$1"
}

if [ "$(basename "$0")" = "$1" ]
then shift
fi
while [ "$#" -gt 0 ]
do
    case "$1" in

        "-h"|"--help") usage 0;;

        *) break;;

    esac
done
if [ -z "$1" ]
then usage 1
fi

# Install the local opener service (from rcrowley's fork of opener to get the
# directory-of-control-sockets variant of jomiller's auto-forwarding patch) to
# catch URLs from the remote xdg-open stand-in.
echo "Installing opener locally to open browser windows for OAuth flows on Panboticon instances ..." >&2
if ! which "opener" >"/dev/null"
then
    if [ -d "$HOME/var/cache/opener" ]
    then git -C "$HOME/var/cache/opener" pull "origin" "$(git -C "$HOME/var/cache/opener" branch --show-current)"
    else git clone -b "multiple-control-sockets" "https://github.com/rcrowley/opener.git" "$HOME/var/cache/opener"
    fi
    (cd "$HOME/var/cache/opener" && go install) # TODO drop the local Go toolchain requirement
fi
which "opener"
mkdir -p "$HOME/Library/LaunchAgents"
cat >"$HOME/Library/LaunchAgents/opener.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key><string>opener</string>
        <key>ProgramArguments</key><array><string>/Users/rcrowley/bin/opener</string></array>
        <key>KeepAlive</key><true/>
        <key>StandardOutPath</key><string>/tmp/opener.stdout</string>
        <key>StandardErrorPath</key><string>/tmp/opener.stderr</string>
    </dict>
</plist>
EOF
launchctl unload "$HOME/Library/LaunchAgents/opener.plist" || :
launchctl load "$HOME/Library/LaunchAgents/opener.plist"
mkdir -p "$HOME/.config/opener"
cat >"$HOME/.config/opener/config.yaml" <<EOF
auto-forward-control-socket-directory: ~/.ssh/control
auto-forward-ttl: 60s
EOF
echo "... Done!" >&2

# Bootstrap each Panboticon instance given as an argument.
STATUS=0
while [ "$#" -gt 0 ]
do
    NAME="$1" shift
    if [ ! -f "$HOME/.ssh/$NAME.ssh_config" ]
    then
        echo "Could not find Panboticon instance $NAME to bootstrap." >&2
        STATUS=1
        continue
    fi

    GITHUB_APP_USER_ID="$(curl -s "https://api.github.com/users/$PANBOTICON_BOT_USER%5Bbot%5D" | jq -e -r '.id')"
    if [ -z "$GITHUB_APP_USER_ID" ]
    then
        echo "Could not find the GitHub App $PANBOTICON_BOT_USER to configure bot GitHub access." >&2
        STATUS=1
        continue
    fi

    echo "Bootstrapping Panboticon instance $NAME ..." >&2

    # Install gh, iptables-persistent, screen, and tmux - almost everything we
    # need to let the bot run wild in its cell.
    ssh "$NAME" sudo DEBIAN_FRONTEND="noninteractive" apt-get -y install "gh" "iptables-persistent" "netcat-openbsd" "screen" "tmux"

    # Deny access to the EC2 IMDS before any human or bot user code runs.
    if ! ssh "$NAME" sudo iptables-save | grep -F -e "-A OUTPUT -d 169.254.169.254/32 -m owner --uid-owner 10101 -j REJECT" -q
    then ssh "$NAME" sudo iptables -I OUTPUT -d "169.254.169.254/32" -m owner --uid-owner "$PANBOTICON_BOT_USER" -j REJECT
    fi
    if ! ssh "$NAME" sudo ip6tables-save | grep -F -e "-A OUTPUT -d fd00:ec2::254/128 -m owner --uid-owner 10101 -j REJECT" -q
    then ssh "$NAME" sudo ip6tables -I OUTPUT -d "fd00:ec2::254/128" -m owner --uid-owner "$PANBOTICON_BOT_USER" -j REJECT
    fi

    # Wire up the ability to open browser tabs on the human user's laptop from
    # inside a Panboticon instance.
    ssh "$NAME" sudo tee "/usr/local/bin/xdg-open" >"/dev/null" <<'EOF'
#!/bin/sh
set -e
if [ "$1" ]
then echo "$@"
else cat
fi | nc -U "$HOME/.opener.sock"
EOF
    ssh "$NAME" sudo chmod +x "/usr/local/bin/xdg-open"
    ssh "$NAME" sudo ln -f -s "xdg-open" "/usr/local/bin/open"

    # Authenticate both the human and the bot with GitHub. These boxen are
    # after all also usable by the human as regular development machines.
    echo "Authenticating human and bot user with GitHub ..." >&2
    echo "Running \`gh auth login\` for the human user, $PANBOTICON_HUMAN_USER." >&2
    ssh "$NAME" gh auth status \|\| gh auth login
    ssh "$NAME" git config --global "credential.https://github.com.helper" "'"'!/usr/bin/env gh auth git-credential'"'"
    ssh "$NAME" git config --global "credential.https://github.com.useHttpPath" "true"
    ssh "$NAME" git config --global "user.email" "$PANBOTICON_HUMAN_EMAIL"
    echo >&2
    echo "Configuring Git access for the bot user's GitHub App, $PANBOTICON_BOT_USER[bot]. " >&2
    ssh -b "$NAME" mkdir -p "/home/$PANBOTICON_BOT_USER/bin" "/home/$PANBOTICON_BOT_USER/.panboticon"
    scp "$PANBOTICON_LIB/gh" "$PANBOTICON_BOT_USER@$NAME:bin/gh"
    scp "$PANBOTICON_LIB/panboticon-git-credential" "$PANBOTICON_BOT_USER@$NAME:bin/panboticon-git-credential"
    echo "$PANBOTICON_BOT_GITHUB_APP_ID" |
    ssh -b "$NAME" tee "/home/$PANBOTICON_BOT_USER/.panboticon/github_app_id.txt" >"/dev/null"
    echo "$PANBOTICON_BOT_GITHUB_APP_INSTALLATIONS" |
    ssh -b "$NAME" tee "/home/$PANBOTICON_BOT_USER/.panboticon/github_app_installations.json" >"/dev/null"
    ssh -b "$NAME" touch "/home/$PANBOTICON_BOT_USER/.panboticon/github_app_private_key.pem"
    ssh -b "$NAME" chmod 600 "/home/$PANBOTICON_BOT_USER/.panboticon/github_app_private_key.pem"
    if [ -f "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" ]
    then scp "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" "$PANBOTICON_BOT_USER@$NAME:.panboticon/github_app_private_key.pem"
    elif echo "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" | grep -q "^op://"
    then
        op read "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" |
        ssh -b "$NAME" tee "/home/$PANBOTICON_BOT_USER/.panboticon/github_app_private_key.pem" >"/dev/null"
    else
        echo "Could not find the GitHub App private key $PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY. The bot user will not have GitHub access yet." >&2
        STATUS=1
    fi
    ssh -b "$NAME" git config --global "credential.https://github.com.helper" "'"'!'"/home/$PANBOTICON_BOT_USER/bin/panboticon-git-credential'"
    ssh -b "$NAME" git config --global "credential.https://github.com.useHttpPath" "true"
    ssh -b "$NAME" git config --global "credential.https://github.com.username" "x-access-token"
    ssh -b "$NAME" git config --global "init.defaultBranch" "main"
    ssh -b "$NAME" git config --global --replace-all "url.https://github.com/.insteadOf" "git@github.com:"
    ssh -b "$NAME" git config --add --global "url.https://github.com/.insteadOf" "ssh://git@github.com/"
    ssh -b "$NAME" git config --global "user.email" "$GITHUB_APP_USER_ID+$PANBOTICON_BOT_USER\[bot\]@users.noreply.github.com"
    ssh -b "$NAME" git config --global "user.name" "$PANBOTICON_BOT_USER\[bot\]"
    echo >&2
    echo "... Done!" >&2

    # Install OpenCode and Pi.
    ssh "$NAME" "\$HOME/.opencode/bin/opencode" upgrade \|\| curl -L -S -f -s "https://opencode.ai/install" \| bash -s -- --no-modify-path
    ssh -b "$NAME" "\$HOME/.opencode/bin/opencode" upgrade \|\| curl -L -S -f -s "https://opencode.ai/install" \| bash -s -- --no-modify-path
    ssh "$NAME" "\$HOME/.local/bin/pi" update --all \|\| curl -L -S -f -s "https://pi.dev/install.sh" \| sh
    ssh -b "$NAME" "\$HOME/.local/bin/pi" update --all \|\| curl -L -S -f -s "https://pi.dev/install.sh" \| sh

    # Run additional configured bootstrapping programs for both human and bot.
    if [ -f "$PANBOTICON_HUMAN_BOOTSTRAP" ]
    then
        scp -r "$HOME/.gnupg" "$PANBOTICON_HUMAN_USER@$NAME:" # XXX HERE BE DRAGONS (surely this is just a bad idea but I don't have a better one)
        EXT="${PANBOTICON_HUMAN_BOOTSTRAP##*.}"
        scp "$PANBOTICON_HUMAN_BOOTSTRAP" "$PANBOTICON_HUMAN_USER@$NAME:panboticon-bootstrap.$EXT"
        case "$EXT" in
            "go") ssh "$NAME" go run "panboticon-bootstrap.$EXT";;
            "py") ssh "$NAME" python "panboticon-bootstrap.$EXT";;
            "rb") ssh "$NAME" ruby "panboticon-bootstrap.$EXT";;
            *) ssh "$NAME" "$EXT" "panboticon-bootstrap.$EXT";;
        esac
    fi
    if [ -f "$PANBOTICON_BOT_BOOTSTRAP" ]
    then
        EXT="${PANBOTICON_BOT_BOOTSTRAP##*.}"
        scp "$PANBOTICON_BOT_BOOTSTRAP" "$PANBOTICON_BOT_USER@$NAME:panboticon-bootstrap.$EXT"
        case "$EXT" in
            "go") ssh -b "$NAME" go run "panboticon-bootstrap.$EXT";;
            "py") ssh -b "$NAME" python "panboticon-bootstrap.$EXT";;
            "rb") ssh -b "$NAME" ruby "panboticon-bootstrap.$EXT";;
            *) ssh -b "$NAME" "$EXT" "panboticon-bootstrap.$EXT";;
        esac
    fi

    # Save the iptables(8) rules that deny the bot user access to the EC2 IMDS
    # and rules added by Docker, Tailscale, or whatever else the configured
    # bootstrapping programs installed.
    ssh "$NAME" sudo netfilter-persistent save

    # Make sure auditd is running and alert the user if it's not.
    if ! ssh "$NAME" sudo systemctl status "auditd" >"/dev/null" 2>"/dev/null"
    then
        ssh "$NAME" sudo systemctl start "auditd"
        ssh "$NAME" sudo systemctl status "auditd"
    fi

    echo "... Done!" >&2
done
exit "$STATUS"
