#!/bin/sh

set -e

usage() {
    printf "Usage: panboticon bootstrap \e[4mname\e[0m [\e[4m...\e[0m]\n" >&2
    printf "  \e[4mname\e[0m  name of the Panboticon instance to bootstrap\n" >&2
    exit "$1"
}

if [ "$(basename "$0")" = "$1" ]
then shift
fi
while [ "$#" -gt 0 ]
do
    case "$1" in

        "-h"|"--help") usage 0;;

        *) break;;

    esac
done
if [ -z "$1" ]
then usage 1
fi

. "$PANBOTICON_LIB/sh.sh"

# Install the local opener service (from rcrowley's fork of opener to get the
# directory-of-control-sockets variant of jomiller's auto-forwarding patch) to
# catch URLs from the remote xdg-open stand-in.
echo "Installing opener locally to open browser windows for OAuth flows on Panboticon instances ..." >&2
mkdir -p "$HOME/.panboticon/bin" "$HOME/.panboticon/etc" "$HOME/.panboticon/log" "$HOME/.panboticon/run"
if [ ! -x "$HOME/.panboticon/bin/opener" ]
then
    curl -L -S -f -o "$TMP/opener.zip" -s "https://github.com/$PANBOTICON_OPENER_FORK/opener/releases/download/$PANBOTICON_OPENER_VERSION/opener-$PANBOTICON_OPENER_OS-$PANBOTICON_GO_ARCH.zip"
    unzip -d "$HOME/.panboticon/bin" -j -o "$TMP/opener.zip" "opener"
fi
[ -x "$HOME/.panboticon/bin/opener" ]
mkdir -p "$HOME/Library/LaunchAgents"
cat >"$HOME/Library/LaunchAgents/panboticon-opener.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>Label</key><string>panboticon-opener</string>
        <key>ProgramArguments</key>
        <array>
            <string>$HOME/.panboticon/bin/opener</string>
            <string>--config</string>
            <string>$HOME/.panboticon/etc/opener.yaml</string>
        </array>
        <key>KeepAlive</key><true/>
        <key>StandardOutPath</key><string>$HOME/.panboticon/log/opener.stdout</string>
        <key>StandardErrorPath</key><string>$HOME/.panboticon/log/opener.stderr</string>
    </dict>
</plist>
EOF
cat >"$HOME/.panboticon/etc/opener.yaml" <<EOF
auto-forward-control-socket-directory: ~/.panboticon/run/control
auto-forward-ttl: 60s
address: ~/.panboticon/run/opener.sock
EOF
launchctl unload "$HOME/Library/LaunchAgents/panboticon-opener.plist" || :
launchctl load "$HOME/Library/LaunchAgents/panboticon-opener.plist"
echo "... Done!" >&2

# Bootstrap each Panboticon instance given as an argument.
STATUS=0
while [ "$#" -gt 0 ]
do
    NAME="$1" shift
    if [ ! -f "$HOME/.panboticon/etc/ssh_config/$NAME.ssh_config" ]
    then
        echo "Could not find Panboticon instance $NAME to bootstrap." >&2
        STATUS=1
        continue
    fi
    echo "Bootstrapping Panboticon instance $NAME ..." >&2

    # Install gh, iptables-persistent, screen, and tmux - almost everything we
    # need to let the bot run wild in its cell.
    sh_q ssh "$NAME" sudo DEBIAN_FRONTEND="noninteractive" apt-get -y install "gh" "iptables-persistent" "netcat-openbsd" "screen" "tmux"

    # Deny the bot user access to the certain CIDR prefixes. We do this early
    # to prevent abuses by the custom bot bootstrap program.
    echo "$PANBOTICON_BOT_REJECT_CIDR_PREFIXES" |
    jq -e -r '.[]' |
    while read CIDR_PREFIX
    do
        SIX=
        if echo "$PREFIX" | grep -q ':'
        then SIX=6
        fi
        if ! ssh "$NAME" sudo ip${SIX}tables-save | grep -F -e "-A OUTPUT -d $CIDR_PREFIX -m owner --uid-owner 10101 -j REJECT" -q
        then ssh "$NAME" sudo ip${SIX}tables -I OUTPUT -d "$CIDR_PREFIX" -m owner --uid-owner "$PANBOTICON_BOT_USER" -j REJECT
        fi
    done

    # Wire up the ability to open browser tabs on the human user's laptop from
    # inside a Panboticon instance.
    ssh "$NAME" sudo tee "/usr/local/bin/xdg-open" >"/dev/null" <<'EOF'
#!/bin/sh
set -e
if [ "$1" ]
then echo "$@"
else cat
fi | nc -U "$HOME/.panboticon/run/opener/$OPENER_SOCKET_C.sock"
EOF
    ssh "$NAME" sudo chmod +x "/usr/local/bin/xdg-open"
    ssh "$NAME" sudo ln -f -s "xdg-open" "/usr/local/bin/open"

    # Authenticate the human user with GitHub.
    echo "Authenticating the human user, $PANBOTICON_HUMAN_USER, with GitHub ..." >&2
    ssh "$NAME" gh auth status \|\| gh auth login
    ssh "$NAME" git config --global "credential.https://github.com.helper" "'"'!/usr/bin/env gh auth git-credential'"'"
    ssh "$NAME" git config --global "credential.https://github.com.useHttpPath" "true"
    ssh "$NAME" git config --global "user.email" "$PANBOTICON_HUMAN_EMAIL"
    echo "... Done!" >&2

    # Configure Git access for the bot user's GitHub App.
    echo "Configuring Git access for the bot user's GitHub App, $PANBOTICON_BOT_USER[bot] ..." >&2
    GITHUB_APP_USER_ID="$(curl -s "https://api.github.com/users/$PANBOTICON_BOT_USER%5Bbot%5D" | jq -e -r '.id')"
    if [ -z "$GITHUB_APP_USER_ID" ]
    then
        echo "Could not find the GitHub App $PANBOTICON_BOT_USER to configure bot GitHub access." >&2
        STATUS=1
        continue
    fi
    ssh "$NAME" mkdir -p ".panboticon"
    ssh "$NAME" mkdir -m 0700 -p ".panboticon/run/control"
    ssh -b "$NAME" mkdir -p ".panboticon/bin" ".panboticon/etc/github-app" "bin"
    ssh -b "$NAME" mkdir -m 0750 -p ".panboticon/run/control"
    scp -b -q "$PANBOTICON_LIB/gh" "$NAME:bin/gh"
    scp -b -q "$PANBOTICON_LIB/git" "$NAME:bin/git"
    scp -b -q "$PANBOTICON_LIB/git-commit-verified" "$NAME:bin/git-commit-verified"
    scp -b -q "$PANBOTICON_LIB/git-credential-helper" "$NAME:.panboticon/bin/git-credential-helper"
    echo "$PANBOTICON_BOT_GITHUB_APP_ID" |
    ssh -b "$NAME" sh -c "'"'tee "'".panboticon/etc/github-app/id.txt"'" >"/dev/null"'"'"
    echo "$PANBOTICON_BOT_GITHUB_APP_INSTALLATIONS" |
    ssh -b "$NAME" sh -c "'"'tee "'".panboticon/etc/github-app/installations.json"'" >"/dev/null"'"'"
    ssh -b "$NAME" sh -c "'"'touch "'".panboticon/etc/github-app/private-key.pem"'"'"'"
    ssh -b "$NAME" sh -c "'"'chmod 0640 "'".panboticon/etc/github-app/private-key.pem"'"'"'"
    if [ -f "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" ]
    then scp -b -q "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" "$NAME:.panboticon/etc/github-app/private-key.pem"
    elif echo "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" | grep -q "^op://"
    then
        op read "$PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY" |
        ssh -b "$NAME" sh -c "'"'tee "'".panboticon/etc/github-app/private-key.pem"'" >"/dev/null"'"'"
    else
        echo "Could not find the GitHub App private key $PANBOTICON_BOT_GITHUB_APP_PRIVATE_KEY. The bot user will not have GitHub access yet." >&2
        STATUS=1
    fi
    ssh -b "$NAME" git config --global "credential.https://github.com.helper" "'"'!'"~/.panboticon/bin/git-credential-helper'"
    ssh -b "$NAME" git config --global "credential.https://github.com.useHttpPath" "true"
    ssh -b "$NAME" git config --global "credential.https://github.com.username" "x-access-token"
    ssh -b "$NAME" git config --global "init.defaultBranch" "main"
    ssh -b "$NAME" git config --global --replace-all "url.https://github.com/.insteadOf" "git@github.com:"
    ssh -b "$NAME" git config --add --global "url.https://github.com/.insteadOf" "ssh://git@github.com/"
    ssh -b "$NAME" git config --global "user.email" "$GITHUB_APP_USER_ID+$PANBOTICON_BOT_USER\[bot\]@users.noreply.github.com"
    ssh -b "$NAME" git config --global "user.name" "$PANBOTICON_BOT_USER\[bot\]"
    echo "... Done!" >&2

    # Run additional configured bootstrapping programs for both human and bot.
    if [ -f "$PANBOTICON_HUMAN_BOOTSTRAP" ]
    then
        echo "Running custom bootstrapping program $PANBOTICON_HUMAN_BOOTSTRAP for the human user, $PANBOTICON_HUMAN_USER..." >&2

        # Copy the human user's GPG keyring to their home directory on the
        # Panboticon instance so they can use it to sign commits.
        #
        # TODO As it is not great to copy a private key anywhere, remove this
        # statement in favor of generating a GPG private key and using gh to
        # add it to GitHub.
        scp -q -r "$HOME/.gnupg" "$NAME:"

        EXT="${PANBOTICON_HUMAN_BOOTSTRAP##*.}"
        scp -q "$PANBOTICON_HUMAN_BOOTSTRAP" "$NAME:.panboticon/bootstrap.$EXT"
        case "$EXT" in
            "go") ssh -t "$NAME" go run ".panboticon/bootstrap.$EXT";;
            "py") ssh -t "$NAME" python ".panboticon/bootstrap.$EXT";;
            "rb") ssh -t "$NAME" ruby ".panboticon/bootstrap.$EXT";;
            *) ssh -t "$NAME" "$EXT" ".panboticon/bootstrap.$EXT";;
        esac
        echo "... Done!" >&2
    fi
    if [ -f "$PANBOTICON_BOT_BOOTSTRAP" ]
    then
        echo "Running custom bootstrapping program $PANBOTICON_BOT_BOOTSTRAP for the botuser, $PANBOTICON_BOT_USER..." >&2
        EXT="${PANBOTICON_BOT_BOOTSTRAP##*.}"
        scp -b -q "$PANBOTICON_BOT_BOOTSTRAP" "$NAME:.panboticon/bootstrap.$EXT"
        case "$EXT" in
            "go") ssh -b -t "$NAME" go run ".panboticon/bootstrap.$EXT";;
            "py") ssh -b -t "$NAME" python ".panboticon/bootstrap.$EXT";;
            "rb") ssh -b -t "$NAME" ruby ".panboticon/bootstrap.$EXT";;
            *) ssh -b -t "$NAME" "$EXT" ".panboticon/bootstrap.$EXT";;
        esac
        echo "... Done!" >&2
    fi

    # Save the iptables(8) rules. We do this late because there may be more
    # rules than just the ones added via PANBOTICON_BOT_REJECT_CIDR_PREFIXES.
    #
    # Make sure auditd is running and alert the user if it's not.
    echo "Finishing bootstrapping Panboticon instance $NAME..." >&2
    sh_q ssh "$NAME" sudo netfilter-persistent save
    if ! ssh "$NAME" sudo systemctl status "auditd" >"/dev/null" 2>"/dev/null"
    then
        sh_q ssh "$NAME" sudo systemctl start "auditd"
        sh_q ssh "$NAME" sudo systemctl status "auditd"
    fi
    echo "... Done!" >&2

    echo "All done!" >&2
done
exit "$STATUS"
