#!/bin/sh

set -e

usage() {
    printf "Usage: panboticon config [-f \e[4mformat\e[0m] [\e[4mvariable\e[0m]\n" >&2
    printf "  -f \e[4mformat\e[0m  output format (one of \"env\", \"json\"; defaults to \"env\")\n" >&2
    printf "  \e[4mvariable\e[0m   variable name from the Panboticon configuration to print; incompatible with -f\n" >&2
    exit "$1"
}

FORMAT=""
if [ "$(basename "$0")" = "$1" ]
then shift
fi
while [ "$#" -gt 0 ]
do
    case "$1" in

        "-f"|"--format") FORMAT="$2" shift 2;;
        "-f"*) FORMAT="$(echo "$1" | cut -c"3-")" shift;;
        "--format="*) FORMAT="$(echo "$1" | cut -d"=" -f"2-")" shift;;

        "-h"|"--help") usage 0;;

        *) break;;

    esac
done
if [ "$FORMAT" -a "$1" -o "$2" ]
then usage 1
fi
if [ -z "$FORMAT" ]
then FORMAT="env"
fi

if [ "$1" ]
then
    eval "echo \"\$$1\""
    exit
fi

env |
grep "^PANBOTICON_" |
sort |
case "$FORMAT" in
    "env")
        sed -E '
            s/^(PANBOTICON_[^=]*)=([^[{].*)?$/\1="\2"/
            s/^(PANBOTICON_[^=]*)=([[{].*)$/\1='"'"'\2'"'"'/
        ';;
    "json")
        sed -E '
            s/^(PANBOTICON_[^=]*)=([^[{].*)?$/{"\1": "\2"}/
            s/^(PANBOTICON_[^=]*)=([[{].*)$/{"\1": \2}/
        ' |
        jq -s '. | add';;
    *) usage 1;;
esac
