#!/bin/sh

set -e

usage() {
    printf "Usage: panboticon ssh [-b] [\e[4m...\e[0m] [\e[4mname\e[0m] [\e[4m...\e[0m]\n" >&2
    printf "  -b        SSH as the bot user instead of the human user\n" >&2
    printf "  \e[4mname\e[0m  name of the Panboticon instance to SSH to (inferred from \`panboticon boxen\` if not given and there's only one)\n" >&2
    exit "$1"
}

USER="$PANBOTICON_HUMAN_USER"
if [ "$(basename "$0")" = "$1" ]
then shift
fi
while [ "$#" -gt 0 ]
do
    case "$1" in

        "-b"|"--bot") USER="$PANBOTICON_BOT_USER" shift;;

        "-h"|"--help") usage 0;;

        *) break;;

    esac
done

. "$PANBOTICON_LIB/aws.sh"

SSH="$(
    which -a "ssh" |
    grep -v "$PANBOTICON_LIBEXEC" |
    head -n 1
)"
if [ "$TERM" = "xterm-ghostty" ]
then export TERM="xterm-256color"
fi

if [ -z "$1" ]
then
    boxen >"$TMP/boxen.txt"
    if [ "$(wc -l <"$TMP/boxen.txt")" -eq 1 ]
    then exec "$SSH" -F "$HOME/.panboticon/etc/ssh_config/$(cat "$TMP/boxen.txt").ssh_config" -l "$USER" "$(cat "$TMP/boxen.txt")"
    else usage 1
    fi
fi

for A in "$@"
do
    if [ -f "$HOME/.panboticon/etc/ssh_config/$A.ssh_config" ]
    then exec "$SSH" -F "$HOME/.panboticon/etc/ssh_config/$A.ssh_config" -l "$USER" "$@"
    fi
done
echo "Could not find the name of a Panboticon instance with an SSH configuration amonst the arguments: $*" >&2
exit 1
