#!/bin/sh

set -e

usage() {
    printf "Usage: panboticon terminate [-f] [-r \e[4mregion\e[0m] \e[4mname-or-instance-id\e[0m[...]\n" >&2
    printf "  -f                   force termination without confirmation\n" >&2
    printf "  -r \e[4mregion\e[0m            AWS region (required if not specified in $PANBOTICON_CONFIG or the environment)\n" >&2
    printf "  \e[4mname-or-instance-id\e[0m  AWS EC2 instance Name tag or ID to terminate\n" >&2
    exit "$1"
}

FORCE=""
if [ "$(basename "$0")" = "$1" ]
then shift
fi
while [ "$#" -gt 0 ]
do
    case "$1" in

        "-f"|"--force") FORCE="--force" shift;;

        "-r"|"--region") PANBOTICON_REGION="$2" shift 2;;
        "-r"*) PANBOTICON_REGION="$(echo "$1" | cut -c"3-")" shift;;
        "--region="*) PANBOTICON_REGION="$(echo "$1" | cut -d"=" -f"2-")" shift;;

        "-h"|"--help") usage 0;;

        *) break;;

    esac
done
if [ -z "$1" ]
then usage 1
fi

. "$PANBOTICON_LIB/aws.sh"

while [ "$#" -gt 0 ]
do

    if [ -z "$FORCE" ]
    then
        printf "Searching for uncommitted changes in Git repositories in ~$PANBOTICON_HUMAN_USER and ~$PANBOTICON_BOT_USER on $1 ..." >&2
        DIFF_HUMAN=0 DIFF_BOT=0
        if ! ssh "$1" find "/home/$PANBOTICON_HUMAN_USER" -name ".git" \| xargs dirname \| xargs -I _ sh -c \''cd _ && pwd && git diff --color --exit-code --stat && git diff --cached --color --exit-code --stat'\'
        then DIFF_HUMAN=1
        fi
        if ! ssh -b "$1" find "/home/$PANBOTICON_BOT_USER" -name ".git" \| xargs dirname \| xargs -I _ sh -c \''cd _ && pwd && git diff --color --exit-code --stat && git diff --cached --color --exit-code --stat'\'
        then DIFF_BOT=1
        fi
        echo " Done!" >&2
        if [ "$DIFF_HUMAN" = 1 ]
        then echo "There are uncommitted changes in Git repositories in ~$PANBOTICON_HUMAN_USER." >&2
        fi
        if [ "$DIFF_BOT" = 1 ]
        then echo "There are uncommitted changes in Git repositories in ~$PANBOTICON_BOT_USER." >&2
        fi
        printf "Are you sure you want to terminate $1? There is no undo. [yn] " >&2
        read YESNO
        case "$YESNO" in
            "y"|"Y"|"yes"|"YES"|"Yes") ;;
            *)
                shift
                continue;;
        esac
    fi

    if [ -f "$HOME/.ssh/$1.ssh_config" ]
    then awk '/^    # i-/ {print $2}' "$HOME/.ssh/$1.ssh_config"

    elif echo "$1" | grep -q "^i-"
    then echo "$1"

    else
        aws ec2 describe-instances --filters \
            Name="ip-address",Values="$1" |
        jq -r '.Reservations[].Instances[].InstanceId'

    fi
    shift
done |
while read INSTANCE_ID
do
    find "$HOME/.ssh" -name "*.ssh_config" |
    xargs grep -E -l '^    # '"$INSTANCE_ID"'$' |
    xargs rm -f
    echo "$INSTANCE_ID"
done |
xargs aws ec2 terminate-instances --instance-ids
