#!/bin/sh

set -e

usage() {
    printf "Usage: %s erase|get|store\n" "$(basename "$0")" >&2
    exit "$1"
}

case "$1" in
    "erase") exit 0;;
    "get") ;; # fallthrough
    "store") exit 0;;
    "-h"|"--help") usage 0;;
    *) usage 1;;
esac

PROTOCOL="" HOST=""
while IFS='=' read -r KEY VALUE
do
    case "$KEY" in
        "") break;;
        "host")
            if [ "$VALUE" != "github.com" ]
            then exit 0
            fi;;
        "protocol")
            if [ "$VALUE" != "https" ]
            then exit 0
            fi;;
        "username")
            if [ "$VALUE" != "x-access-token" ]
            then exit 0
            fi;;
        "wwwauth[]")
            if [ "$VALUE" != "Basic realm=\"GitHub\"" ]
            then exit 0
            fi;;
        *) echo "Unexpected input \`$KEY=$VALUE\`." >&2;;
    esac
done

NOW="$(date +"%s")"

if [ -f "$HOME/.cache/panboticon-git-credential.json" ]
then
    EXPIRY="$(jq -e -r '.expires_at | fromdateiso8601' <"$HOME/.cache/panboticon-git-credential.json")"
    if [ "$((EXPIRY - NOW))" -gt 60 ]
    then
        printf "username=x-access-token\npassword="
        jq -e -r '.token' <"$HOME/.cache/panboticon-git-credential.json"
        exit 0
    fi
fi

base64urlencode() {
    openssl base64 -A | tr '+/' '-_' | tr -d '='
}
HEADER="$(printf '{"alg":"RS256","typ":"JWT"}' | base64urlencode)" 
PAYLOAD="$(printf '{"iat":%d,"exp":%d,"iss":"%s"}' "$((NOW - 60))" "$((NOW + 600 - 60))" "$(cat "$HOME/.panboticon/github_app_id.txt")" | base64urlencode)"
SIG="$(printf '%s' "$HEADER.$PAYLOAD" | openssl dgst -sha256 -sign "$HOME/.panboticon/github_app_private_key.pem" | base64urlencode)"
JWT="$(printf '%s.%s.%s' "$HEADER" "$PAYLOAD" "$SIG")"

mkdir -p "$HOME/.cache"
touch "$HOME/.cache/panboticon-git-credential.tmp.json"
chmod 600 "$HOME/.cache/panboticon-git-credential.tmp.json"
curl \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $JWT" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -s \
    "https://api.github.com/app/installations/$(
        cat "$HOME/.panboticon/github_app_installation_id.txt"
    )/access_tokens" >"$HOME/.cache/panboticon-git-credential.tmp.json"
mv "$HOME/.cache/panboticon-git-credential.tmp.json" "$HOME/.cache/panboticon-git-credential.json"

printf "username=x-access-token\npassword="
jq -e -r '.token' <"$HOME/.cache/panboticon-git-credential.json"
