#!/bin/sh

set -e

usage() {
    printf "Usage: %s erase|get|store\n" "$(basename "$0")" >&2
    exit "$1"
}

case "$1" in
    "erase") exit 0;;
    "get") ;; # fallthrough
    "store") exit 0;;
    "-h"|"--help") usage 0;;
    *) usage 1;;
esac

ORGANIZATION=""
while IFS='=' read -r KEY VALUE
do
    case "$KEY" in
        "") break;;
        "host") [ "$VALUE" != "github.com" ] && exit 0;;
        "path") ORGANIZATION="${VALUE%%/*}";;
        "protocol") [ "$VALUE" != "https" ] && exit 0;;
        "username") [ "$VALUE" != "x-access-token" ] && exit 0;;
        "wwwauth[]") [ "$VALUE" != "Basic realm=\"GitHub\"" ] && exit 0;;
        *) echo "Unexpected input \`$KEY=$VALUE\`." >&2;;
    esac
done
[ "$ORGANIZATION" ]

APP_ID="$(cat "$HOME/.panboticon/github_app_id.txt")"
INSTALLATION_ID="$(jq -e -r '.[] | select(.ORGANIZATION == "'"$ORGANIZATION"'") | .INSTALLATION_ID' <"$HOME/.panboticon/github_app_installations.json")"

NOW="$(date +"%s")"

if [ -f "$HOME/.cache/panboticon-git-credential/$ORGANIZATION.json" ]
then
    EXPIRY="$(jq -e -r '.expires_at | fromdateiso8601' <"$HOME/.cache/panboticon-git-credential/$ORGANIZATION.json")"
    if [ "$((EXPIRY - NOW))" -gt 60 ]
    then
        printf "username=x-access-token\npassword="
        jq -e -r '.token' <"$HOME/.cache/panboticon-git-credential/$ORGANIZATION.json"
        exit 0
    fi
fi

base64urlencode() {
    openssl base64 -A | tr '+/' '-_' | tr -d '='
}
HEADER="$(printf '{"alg":"RS256","typ":"JWT"}' | base64urlencode)" 
PAYLOAD="$(printf '{"iat":%d,"exp":%d,"iss":"%s"}' "$((NOW - 60))" "$((NOW + 600 - 60))" "$APP_ID" | base64urlencode)"
SIG="$(printf '%s' "$HEADER.$PAYLOAD" | openssl dgst -sha256 -sign "$HOME/.panboticon/github_app_private_key.pem" | base64urlencode)"
JWT="$(printf '%s.%s.%s' "$HEADER" "$PAYLOAD" "$SIG")"

mkdir -p "$HOME/.cache/panboticon-git-credential"
touch "$HOME/.cache/panboticon-git-credential/$ORGANIZATION.tmp.json"
chmod 600 "$HOME/.cache/panboticon-git-credential/$ORGANIZATION.tmp.json"
curl \
    -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $JWT" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    -s \
    "https://api.github.com/app/installations/$INSTALLATION_ID/access_tokens" >"$HOME/.cache/panboticon-git-credential/$ORGANIZATION.tmp.json"
mv "$HOME/.cache/panboticon-git-credential/$ORGANIZATION.tmp.json" "$HOME/.cache/panboticon-git-credential/$ORGANIZATION.json"

printf "username=x-access-token\npassword="
jq -e -r '.token' <"$HOME/.cache/panboticon-git-credential/$ORGANIZATION.json"
